
export const villas = [
  {
    id: 1,
    name: "Villa Luna",
    location: "Greece",
    category: "Mountains",
    guests: 11,
    bedrooms: 6,
    bathrooms: 10,
    squareMeter: "400",
    rating: 4.7,
    image: "/villa1.jpg",
    dailyRent: "240",
    src:"https://www.google.com/maps/embed/v1/place?q=place_id:ChIJ0U39L0DMwoARa52r3t4vu3g&key=AIzaSyBFw0Qbyq9zTFTd-tUY6dZWTgaQzuU17R8",
  },
  {
    id: 2,
    name: "Villa Tosco",
    location: "Italy",
    category: "Mountains",
    guests: 8,
    bedrooms: 8,
    bathrooms: 12,
    squareMeter: "450",
    rating: 4.4,
    image: "/villa2.jpg",
    dailyRent: "300",
    src:"https://www.google.com/maps/embed/v1/place?q=Villa%20Tosco&key=AIzaSyBFw0Qbyq9zTFTd-tUY6dZWTgaQzuU17R8"
  },
  {
    id: 3,
    name: "Aphrodite",
    location: "Greece",
    category: "Seaside",
    guests: 12,
    bedrooms: 6,
    bathrooms: 6,
    squareMeter: "500",
    rating: 4.9,
    image: "/villa3.jpg",
    dailyRent: "200",
    src:"https://www.google.com/maps/embed/v1/place?q=place_id:ChIJ9ZvtEw0c5xQRBovJosRCAUA&key=AIzaSyBFw0Qbyq9zTFTd-tUY6dZWTgaQzuU17R8"
  },
  {
    id: 4,
    name: "Villa Makarska",
    location: "Italy",
    category: "Mountains",
    guests: 12,
    bedrooms: 15,
    bathrooms: 20,
    squareMeter: "750",
    rating: 5.0,
    image: "/villa4.jpg",
    dailyRent: "260",
    src:"https://www.google.com/maps/embed/v1/place?q=place_id:ChIJ044AeeDvShMRtwKtCzrLKLI&key=AIzaSyBFw0Qbyq9zTFTd-tUY6dZWTgaQzuU17R8"
  },
  {
    id: 5,
    name: "Villa General Belgrano",
    location: " Argentina",
    category: "Mountains",
    guests: 4,
    bedrooms: 5,
    bathrooms: 6,
    squareMeter: "275",
    rating: 4.0,
    image: "/villa5.jpg",
    dailyRent: "200",
    src:"https://www.google.com/maps/embed/v1/search?q=Villa+General+Belgrano,+Córdoba+Province,+Argentina&key=AIzaSyBFw0Qbyq9zTFTd-tUY6dZWTgaQzuU17R8"
  },
  {
    id: 6,
    name: "Aphrodite",
    location: "Greece",
    category: "Seaside",
    guests: 12,
    bedrooms: 6,
    bathrooms: 6,
    squareMeter: "500",
    rating: 4.9,
    image: "/villa6.jpg",
    dailyRent: "320",
    src:"https://www.google.com/maps/embed/v1/search?q=Aphrodite+Hills,+Kouklia,+Cyprus&key=AIzaSyBFw0Qbyq9zTFTd-tUY6dZWTgaQzuU17R8"
  },
  {
    id: 7,
    name: "Villa Sunset",
    location: "Italy",
    category: "Mountains",
    guests: 15,
    bedrooms: 8,
    bathrooms: 10,
    squareMeter: "1000",
    rating: 4.8,
    image: "/villa7.jpg",
    dailyRent: "280",
    src:"https://www.google.com/maps/embed/v1/search?q=Villa%20Sunset%2C%20Sambikerep%2C%20Bangunjiwo%2C%20Bantul%20Regency%2C%20Special%20Region%20of%20Yogyakarta%2C%20Indonesia&key=AIzaSyBFw0Qbyq9zTFTd-tUY6dZWTgaQzuU17R8"
  },
  {
    id: 8,
    name: "White Lady",
    location: "Italy",
    category: "Seaside",
    guests: 25,
    bedrooms: 25,
    bathrooms: 25,
    squareMeter: "1500",
    rating: 5.0,
    image: "/villa8.jpg",
    dailyRent: "400",
    src:"https://www.google.com/maps/embed/v1/search?q=White%20Lady%20Hotel%2C%20Lower%20O'Connell%20Street%2C%20Dromderrig%2C%20Kinsale%2C%20County%20Cork%2C%20Ireland&key=AIzaSyBFw0Qbyq9zTFTd-tUY6dZWTgaQzuU17R8"
  },
  {
    id: 9,
    name: "Thebes",
    location: "Greece",
    category: "Seaside",
    guests: 5,
    bedrooms: 6,
    bathrooms: 6,
    squareMeter: "240",
    rating: 3.8,
    image: "/villa9.jpg",
    dailyRent: "180",
    src:"https://www.google.com/maps/embed/v1/search?q=Th%C3%A8bes%2C%20Greece&key=AIzaSyBFw0Qbyq9zTFTd-tUY6dZWTgaQzuU17R8"
  },
];

